### ISSUE TITLE
Create a draft proposal.

### ISSUE THREAD

**Issue by SathwikSai10** [RnDProjectsDeebul/SathwikPanchangamRnD#1]
Make the suggested changes.
Add the block diagram
Add figures and numbers to the report.

**Comment by deebuls** [comment]
![UncertaitnyBenchmark](https://user-images.githubusercontent.com/6873193/166300235-1321b49f-ef46-4ca6-ac3b-7cd5e7b22032.jpg)

**Comment by SathwikSai10** [comment]
Completed draft proposal
