### ISSUE TITLE
Midterm Report

### ISSUE THREAD

**Issue by SathwikSai10** [RnDProjectsDeebul/SathwikPanchangamRnD#22]
[https://github.com/RnDProjectsDeebul/SathwikPanchangamRnD/blob/main/Project_proposal/Sathwik_Panchangam_midterm_report.pdf](url)

**Comment by deebuls** [comment]
There is hardly any text to give comment . I can see a lot of images and the final experiment table . But no text atall .
Redo the report, this time address a particular research question and answer it . 
State of art has to be completed . 
Submit by Nov 15th
