### ISSUE TITLE
Answering the question on which all parameters in blender did we use for generation

### ISSUE THREAD

**Issue by deebuls** [RnDProjectsDeebul/SathwikPanchangamRnD#23]
1. We have to answer the question that we used Blender for data generation. In that Blender has so many features which features did we focus on and why .

In order to answer this there is a format called glft2  . The advantage of the format is it is used to describe the scene . And the different parameters required to explain the scene. 
The Blender plugin for the same is below 

https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html

Please after the Nov 15th can you look into this section and write from you Blender experience what do you understand by this plugin. 

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#concepts-general

**Comment by SathwikPanchangam** [comment]
Reported the modifiable parameters of blender for dataset generation
