### ISSUE TITLE
Ensemble Uncertainty Estimation

### ISSUE THREAD

**Issue by deebuls** [RnDProjectsDeebul/SathwikPanchangamRnD#25]
https://towardsdatascience.com/2-easy-ways-to-measure-your-image-classification-models-uncertainty-1c489fefaec8

```
import sys
import numpy as np

def predictive_entropy(predictions):
    epsilon = sys.float_info.min
    predictive_entropy = -np.sum( np.mean(predictions, axis=0) * np.log(np.mean(predictions, axis=0) + epsilon),
            axis=-1)

    return predictive_entropy
```

This was the missing code which was required . 

As you can see the blog. you need to add some lines of code for creating the 5 models

**Comment by SathwikPanchangam** [comment]
Implemented both MC dropout and Ensemble models and reported the results
