### ISSUE TITLE
Final results review

### ISSUE THREAD

**Issue by SathwikSai10** [RnDProjectsDeebul/SathwikPanchangamRnD#27]
[rnd_results.pdf](https://github.com/RnDProjectsDeebul/SathwikPanchangamRnD/files/10368618/rnd_results.pdf)

I have written a report for all the conducted experiments in a colab notebook.
* Link for the colab notebook: (https://colab.research.google.com/drive/1legDi-pRly3F6UecBBp8574hrlAwRogO?usp=sharing)

The data for corresonding results is available in the folder named **28-12-2022** in the google drive 
* Link for the data:[csv files and images of the results] (https://drive.google.com/drive/folders/1pdVgM3gdqAMY0wL7mM01nTJk-8SIYXXN?usp=sharing)

**Comment by SathwikPanchangam** [comment]
Got feedback and changed the plots accordingly
