### ISSUE TITLE
New object dataset  - Hope dataset

### ISSUE THREAD

**Issue by deebuls** [RnDProjectsDeebul/SathwikPanchangamRnD#3]
https://github.com/swtyree/hope-dataset#objects

This a new object dataset. 
Its kids toys .
Cheap and available to purchase in germany .
Model is provided . 

If interesting we can purchase it . 

@SathwikSai10 check the models if its usable in blender .
@deebuls Why should we use this dataset as compared to the YCB/@work

**Comment by SathwikPanchangam** [comment]
Didn't use Hope dataset in the Rnd project
